server:
  port: 8001
  servlet:
    context-path: /spring-with-mongo-db-replica-set

spring:
  data:
    mongodb:
      uri: "mongodb://root:root@primary:27017,replica01:27017,replica02:27017/tutorial-db?authSource=admin&replicaSet=tutorial-cluster&readPreference=secondary"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG