server:
  port: 8001
  servlet:
    context-path: /spring-with-mongo-db-replica-set

spring:
  data:
    mongodb:
      uri: "mongodb://root:example@localhost:27017,localhost:27018,localhost:27019/customers?authSource=admin&replicaSet=rs0&readPreference=secondary"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG