version: "3.8"

services:

  temp-instance:
    container_name: temp-instance
    image: mongo:5.0.5
    volumes:
      - ./init-mongo-db:/docker-entrypoint-initdb.d
    networks:
      - mongo-cluster-network

  primary:
    container_name: primary
    image: mongo:5.0.5
    volumes:
      - ./keys/mongo-replica-set.key:/data/db/mongo-replica-set.key
    ports:
      - "27017:27017"
    environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      mongo-cluster-network:
          ipv4_address: 172.16.238.10
    command:
      - "--replSet"
      - "tutorial-cluster"
      - "--keyFile"
      - "/data/db/mongo-replica-set.key"
      - "--profile=1"
      - "--slowms=1"

  replica01:
    container_name: replica01
    image: mongo:5.0.5
    volumes:
      - ./keys/mongo-replica-set.key:/data/db/mongo-replica-set.key
    ports:
      - "27027:27017"
    networks:
      mongo-cluster-network:
        ipv4_address: 172.16.238.11
    command:
      - "--replSet"
      - "tutorial-cluster"
      - "--keyFile"
      - "/data/db/mongo-replica-set.key"
      - "--profile=1"
      - "--slowms=1"

  replica02:
    container_name: replica02
    image: mongo:5.0.5
    volumes:
      - ./keys/mongo-replica-set.key:/data/db/mongo-replica-set.key
    ports:
      - "27037:27017"
    networks:
      mongo-cluster-network:
        ipv4_address: 172.16.238.12
    command:
      - "--replSet"
      - "tutorial-cluster"
      - "--keyFile"
      - "/data/db/mongo-replica-set.key"
      - "--profile=1"
      - "--slowms=1"

networks:
  mongo-cluster-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24